spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test?prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&cachePrepStmts=true&useServerPrepStmts=true
      username: root
      password:
      maximum-pool-size: 20
      connection-timeout: 24000
      leak-detection-threshold: 24000
      auto-commit: false
    url: ${spring.datasource.hikari.jdbc-url}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update